openapi: 3.0.3
info:
  title: Usuarios
  description: Usuarios
  version: "1.0"

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ALEXEICAMBRAYEACS/RESTJedi/1.0
  - url: http://localhost:8000
    description: Development server

paths:
  /users/{id}:
    get:
      operationId: getUser
      summary: Get a specific user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "4XX":
          description: Bad Request
        "404":
          description: User not found

  /users:
    get:
      operationId: index
      summary: Get the main page of the API
      responses:
        "200":
          description: Success
          content:
            text/plain:
              example: Backed usuarios database

    post:
      operationId: createUser
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "4XX":
          description: Bad Request

    put:
      operationId: updateUser
      summary: Update an existing user
      parameters:
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "4XX":
          description: Bad Request

    delete:
      operationId: deleteUser
      summary: Delete a user
      parameters:
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message confirming the deletion
        "4XX":
          description: Bad Request

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateUserRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string